### ISSUE TITLE
ACPIBacklight not work with OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by Polishapple** [RehabMan/OS-X-ACPI-Backlight#12] opened 2015-06-10 08:04 UTC
Hi, there is a broblem with kext under neew osx. It's completly not working ( its loading but not working)

**Comment by lisai9093** [comment] 2015-06-10 20:30
Confirmed. Remove the kext to get brightness control working.

**Comment by setyosn** [comment] 2015-06-13 02:39
me too..  😂 @lisai9093 basic patch & dsdt patch when we're using acpibacklight so different. i think , it doesn't work when u use acpibacklight dsdt patch without installing acpibacklight.kext.

**Comment by RehabMan** [comment] 2015-06-23 14:23
Problem seems to be in ACPI (new AppleACPIPlatform.kext).  The kext is working fine, but when PNLF (XBCM, etc) goes to write to the backlight registers (or read from them), it is ineffective.  Possible that AppleACPIPlatform is broken, or the device is somehow configured differently than before.

Will require more investigation...

**Comment by Polishapple** [comment] 2015-06-23 18:28
There might be some changes in AppleACPIPlatform, apple also changed the applehda

**Comment by RehabMan** [comment] 2015-06-23 22:56
Of course.  There is definitely changes... AppleACPIPlatform.kext is v4.0 (Yosemite is v3.1).

But I think this is something the new graphics drivers are doing.

IGPU.BAR1 actually changes once the graphics drivers take control.  No so on previous versions.

**Comment by RehabMan** [comment] 2015-06-23 22:58
I may focus some effort on trying to determine why smooth transitions don't happen with native AppleBacklight.kext.

**Comment by Polishapple** [comment] 2015-07-08 16:03
But in El capitan i have to use your kext. Without it the 100% brightnes is like 15%-20%.

**Comment by RehabMan** [comment] 2015-07-08 17:46
> But in El capitan i have to use your kext. Without it the 100% brightnes is like 15%-20%.

Sounds like you didn't properly patch AppleBacklight.kext (or build injector) for your display.

**Comment by Polishapple** [comment] 2015-07-09 06:44
Can you explain how to patch applebacklight or patch edid

**Comment by RehabMan** [comment] 2015-07-10 17:38
Look at my u430 repo: https://github.com/RehabMan/Lenovo-U430-Touch-DSDT-Patch

Use patch_backlight.sh (needs Backlight.plist) to create AppleBacklightInjector.kext for your display.

Note: The u430 is Haswell and this Backlight.plist is for Haswell.  Ivy/Sandy needs different data.

I explained here too: http://www.tonymacx86.com/el-capitan-laptop-support/167963-backlight-control.html

**Comment by RehabMan** [comment] 2015-07-10 17:40
EDID patching involves changing the vendor-id and display-id in the EDID to match a display already in AppleBacklight.kext Info.plist (with appropriate range for graphics chip).  You would need to read about EDID, extract your own, study the Info.plist, change the two items I mention, and inject it.  EDID is easily injected with Clover (read the Clover wiki).

**Comment by Polishapple** [comment] 2015-07-12 13:16
Ok. :> But i don't understand those panels in applebacklight.kext. Wich is good for HD3000?

**Comment by RehabMan** [comment] 2015-07-13 18:44
> IGPU.BAR1 actually changes once the graphics drivers take control. Not so on previous versions.

Not only that, but if you capture it on each call to _BCM, writes there still don't work although the BAR1 I read in ACPI correlates to what I see with IOPCIDevice->configRead.

I'll try writing directly from the kext instead of going through ACPI.

**Comment by RehabMan** [comment] 2015-07-13 22:05
> But i don't understand those panels in applebacklight.kext. Wich is good for HD3000?

Any that has a range of 0-0x710 is good for Ivy/Sandy.

Try the script in the post thread I linked (there is now an Ivy/Sandy version on the ProBook repo).

**Comment by RehabMan** [comment] 2015-07-14 01:33
I have it working.  Access directly from the kext to the backlight registers works.

Now I need to decide how I really want to code for this change.

**Comment by RehabMan** [comment] 2015-07-15 15:55
Fixed in commit 1694e8b2b0b3a812757444e15a978ed789853cec.

This is due to the drivers changing BAR1 to a new address during initialization.  This memory cannot be mapped to SystemMemory in ACPI so all access fails.

To workaround this limitation, I'm setting the registers in the kext itself (IntelBacklightHandler) instead of calling into XBCM/XBQC in ACPI.

**Closed by RehabMan** 2015-07-15 15:55 UTC

**Comment by setyosn** [comment] 2015-07-16 07:12
good job (y)

**Comment by lisai9093** [comment] 2015-07-16 10:00
Awesome! Verified working under 10.11
