### ISSUE TITLE
Full Range Brightness Without ACPIBacklight

### ISSUE THREAD

**Issue by setyosn** [RehabMan/OS-X-ACPI-Backlight#13] opened 2015-06-15 09:22 UTC
how to get full range of brightness without acpibacklight? coz, it didn't worked on El Capitan.

**Comment by Polishapple** [comment] 2015-06-16 07:01
Just wait for new bulid

**Comment by RehabMan** [comment] 2015-06-23 14:24
duplicate of #12.

**Closed by RehabMan** 2015-06-23 14:24 UTC
